### ISSUE TITLE
Template doesn't work in 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by itmuecke** [ipari/dokuwiki-template-white#10]
After upgrading last version of dokuwiki to 2018-04-22 "Greebo", the website with template white installed shows an error:
"A fatal error occured during compilation of the CSS files. If you ... [.linear-gradient is undefined: failed at '' in /lib/tpl/white/css/basic.less at line 389]"

Do you need any information about this ting?
I cant show you the website, cause I need it without the error and will choose now another template as a workaround :(

Thanks for your help and this template 👍 

Screenshot:
![grafik](https://user-images.githubusercontent.com/38725532/39248405-47548042-489c-11e8-961a-2502b365dd89.png)

**Comment by ipari** [comment]
Hi, I'll see this issue on this weekend.
Thanks for your report!

**Comment by ipari** [comment]
Released new version for 2018-04-22 for this issue.
Would you check it working?

**Comment by itmuecke** [comment]
It works. Thanks a lot for your quick help! Great work.

Best regards, Richard.
